"""initial

Revision ID: 144038aa4052
Revises: 
Create Date: 2026-02-22 12:56:43.867484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144038aa4052'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('client_gln', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('identification_type', sa.Integer(), nullable=True),
    sa.Column('identification_code', sa.String(length=10), nullable=True),
    sa.Column('identification_number', sa.String(length=50), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('nationality', sa.String(length=3), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_country_code', sa.String(length=10), nullable=True),
    sa.Column('phone_area_code', sa.String(length=10), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('phone_description', sa.String(length=50), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index('idx_client_company_gln_nationality', 'clients', ['company_id', 'client_gln', 'nationality'], unique=True)
    op.create_index('idx_client_company_id', 'clients', ['company_id'], unique=False)
    op.create_table('departments',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('department_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('supplier_code', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_index('idx_department_client_code', 'departments', ['client_id', 'department_code'], unique=True)
    op.create_index('idx_department_client_id', 'departments', ['client_id'], unique=False)
    op.create_index('idx_department_company_id', 'departments', ['company_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('track_inventory', sa.Boolean(), nullable=False),
    sa.Column('is_service', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('on_sale', sa.Boolean(), nullable=False),
    sa.Column('original_price', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('internal_code', sa.String(length=50), nullable=True),
    sa.Column('original_code', sa.String(length=50), nullable=True),
    sa.Column('client_article_code', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('units_per_box', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_org_internal_code', 'products', ['organization_id', 'internal_code'], unique=True)
    op.create_table('stores',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('store_code', sa.String(length=20), nullable=False),
    sa.Column('store_name', sa.String(length=200), nullable=True),
    sa.Column('slot_id', sa.String(length=20), nullable=True),
    sa.Column('chain', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index('idx_store_client_id', 'stores', ['client_id'], unique=False)
    op.create_index('idx_store_company_client_code', 'stores', ['company_id', 'client_id', 'store_code'], unique=True)
    op.create_index('idx_store_company_id', 'stores', ['company_id'], unique=False)
    op.create_table('crossdocking_confirmations',
    sa.Column('confirmation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('confirmation_number', sa.String(length=100), nullable=False),
    sa.Column('delivery_date', sa.String(length=20), nullable=True),
    sa.Column('confirmation_status', sa.String(length=20), nullable=True),
    sa.Column('deliver_to_store_id', sa.UUID(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deliver_to_store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('confirmation_id')
    )
    op.create_index('idx_confirmation_company_id', 'crossdocking_confirmations', ['company_id'], unique=False)
    op.create_index('idx_confirmation_company_number', 'crossdocking_confirmations', ['company_id', 'confirmation_number'], unique=True)
    op.create_table('crossdocking_orders',
    sa.Column('order_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('creation_date', sa.String(length=20), nullable=True),
    sa.Column('delivery_date', sa.String(length=20), nullable=True),
    sa.Column('order_status', sa.String(length=20), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('discounts', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('net_total', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('taxes', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('total_quantities', sa.BigInteger(), nullable=True),
    sa.Column('line_count', sa.BigInteger(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('bgm011', sa.String(length=50), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('event', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('crossdocking_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('nuevo_reporte_url', sa.String(length=500), nullable=True),
    sa.Column('excel_url', sa.String(length=500), nullable=True),
    sa.Column('crossdocking_excel_url', sa.String(length=500), nullable=True),
    sa.Column('confirmation_id', sa.BigInteger(), nullable=True),
    sa.Column('confirmation_number', sa.String(length=100), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('deliver_to_store_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['confirmation_id'], ['crossdocking_confirmations.confirmation_id'], ),
    sa.ForeignKeyConstraint(['deliver_to_store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index('idx_order_company_document', 'crossdocking_orders', ['company_id', 'document_number'], unique=True)
    op.create_index('idx_order_company_id', 'crossdocking_orders', ['company_id'], unique=False)
    op.create_index('idx_order_document_number', 'crossdocking_orders', ['document_number'], unique=False)
    op.create_table('crossdocking_order_lines',
    sa.Column('line_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('line_number', sa.BigInteger(), nullable=False),
    sa.Column('quantity_ordered', sa.BigInteger(), nullable=True),
    sa.Column('units_ordered', sa.BigInteger(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('discount', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('tax', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('quantity_dispatched', sa.BigInteger(), nullable=True),
    sa.Column('dispatch_rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('quantity_received', sa.BigInteger(), nullable=True),
    sa.Column('article_code', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['crossdocking_orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('line_id')
    )
    op.create_index('idx_order_line_order_id', 'crossdocking_order_lines', ['order_id'], unique=False)
    op.create_table('crossdocking_sale_points',
    sa.Column('sale_point_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=250), nullable=True),
    sa.Column('total_boxes', sa.BigInteger(), nullable=True),
    sa.Column('total_units', sa.BigInteger(), nullable=True),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['crossdocking_orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('sale_point_id')
    )
    op.create_index('idx_crossdocking_sp_order_id', 'crossdocking_sale_points', ['order_id'], unique=False)
    op.create_table('crossdocking_items',
    sa.Column('item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sale_point_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=True),
    sa.Column('total_units', sa.BigInteger(), nullable=True),
    sa.Column('sent', sa.BigInteger(), nullable=True),
    sa.Column('missing', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_point_id'], ['crossdocking_sale_points.sale_point_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('idx_crossdocking_item_sp_id', 'crossdocking_items', ['sale_point_id'], unique=False)
    op.add_column('categories', sa.Column('image_1_url', sa.Text(), nullable=True))
    op.add_column('categories', sa.Column('image_2_url', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('gln', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('internal_code', sa.String(length=50), nullable=True))
    # management-be may already have provisioned the shared organization logo.
    op.execute('ALTER TABLE organizations ADD COLUMN IF NOT EXISTS logo_url VARCHAR(500)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'logo_url')
    op.drop_column('organizations', 'internal_code')
    op.drop_column('organizations', 'gln')
    op.drop_column('categories', 'image_2_url')
    op.drop_column('categories', 'image_1_url')
    op.drop_index('idx_crossdocking_item_sp_id', table_name='crossdocking_items')
    op.drop_table('crossdocking_items')
    op.drop_index('idx_crossdocking_sp_order_id', table_name='crossdocking_sale_points')
    op.drop_table('crossdocking_sale_points')
    op.drop_index('idx_order_line_order_id', table_name='crossdocking_order_lines')
    op.drop_table('crossdocking_order_lines')
    op.drop_index('idx_order_document_number', table_name='crossdocking_orders')
    op.drop_index('idx_order_company_id', table_name='crossdocking_orders')
    op.drop_index('idx_order_company_document', table_name='crossdocking_orders')
    op.drop_table('crossdocking_orders')
    op.drop_index('idx_confirmation_company_number', table_name='crossdocking_confirmations')
    op.drop_index('idx_confirmation_company_id', table_name='crossdocking_confirmations')
    op.drop_table('crossdocking_confirmations')
    op.drop_index('idx_store_company_id', table_name='stores')
    op.drop_index('idx_store_company_client_code', table_name='stores')
    op.drop_index('idx_store_client_id', table_name='stores')
    op.drop_table('stores')
    op.drop_index('idx_product_org_internal_code', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_department_company_id', table_name='departments')
    op.drop_index('idx_department_client_id', table_name='departments')
    op.drop_index('idx_department_client_code', table_name='departments')
    op.drop_table('departments')
    op.drop_index('idx_client_company_id', table_name='clients')
    op.drop_index('idx_client_company_gln_nationality', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
